### ISSUE TITLE
Alphanumeric figure, finding, table ordinals

### ISSUE THREAD

**Issue by abuddenb** [USGCRP/gcis#484]
/report/noaa-led-state-summaries-2017 contains a large number of figures with alphanumeric ordinals (eg. 1, 2, 3, 4a, 4b, 4c, 4d, 5, 6, 7)

Can we alter validation on Figure's ordinal field to accept alphanumerics (eg "4a").

**Comment by lomky** [comment]
@abuddenb we can and will. 

Currently the `Figure` `Ordinal` is defined as [type]() `integer`. I will change it to `character varying` and update the comment to explain the expected data.

**Comment by lomky** [comment]
## Task List

   - [ ]  update the DB entry (patch)
   - [ ]  update Figure Control show function to accept alphanumeric
   - [ ]  confirm new figure ordinals will sort properly
   - [ ]  investigate figure manager will handle dbgrep properly
   - [ ]  decide if Table & Finding `ordinal` should also be updated
     - [ ]  update them if needed, following path of Figure
   - [ ]  extend Figure and Report tests
   - [ ]  update DB documentation

**Comment by lomky** [comment]
Splitting off the sorting issue into a lower priority follow on ticket. For now sorting will function as Finding does today (lexicographically: 1, 10, 2, 20, 2b, 2c-1). End goal is sorting alphabetically/numerically (1, 2, 2b, 2c-1, 10, 20)
